<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.93.0" />


<title>IS 407 Lab 01 Team Project - A Hugo website</title>
<meta property="og:title" content="IS 407 Lab 01 Team Project - A Hugo website">


  <link href='/favicon.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/logo.png"
         width="50"
         height="50"
         alt="Logo">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/rstudio/blogdown">GitHub</a></li>
    
    <li><a href="https://twitter.com/rstudio">Twitter</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">15 min read</span>
    

    <h1 class="article-title">IS 407 Lab 01 Team Project</h1>

    
    <span class="article-date">2022-02-15</span>
    

    <div class="article-content">
      
<script src="/2022/02/15/is-407-hw-02/index_files/header-attrs/header-attrs.js"></script>


<div id="lab1---nobel-laureates" class="section level1">
<h1>Lab1 - Nobel laureates</h1>
<p>In January 2017, Buzzfeed published an article on why Nobel laureates show immigration is so important for American science.
You can read the article <a href="https://www.buzzfeednews.com/article/peteraldhous/immigration-and-science">here</a>.
In the article they show that while most living Nobel laureates in the sciences are based in the US, many of them were born in other countries.
This is one reason why scientific leaders say that immigration is vital for progress.
In this lab we will work with the data from this article to recreate some of their visualizations as well as explore new questions.</p>
</div>
<div id="learning-goals" class="section level1">
<h1>Learning goals</h1>
<ul>
<li>Collaborating on GitHub and resolving merge conflicts</li>
<li>Replicating published results</li>
<li>Data wrangling and visualisation</li>
</ul>
</div>
<div id="lab-prep" class="section level1">
<h1>Lab prep</h1>
<p>You have two tasks you should complete before the lab:</p>
<ul>
<li><strong>Task 1:</strong> Read the Buzzfeed article titled <a href="https://www.buzzfeednews.com/article/peteraldhous/immigration-and-science"><em>These Nobel Prize Winners Show Why Immigration Is So Important For American Science</em></a><em>.</em> We will replicate this analysis in the workshop so it’s crucial that you’re familiar with it ahead of time.</li>
<li><strong>Task 2:</strong> Read about merge conflicts below. The merge conflict exercise we’ll start with during the lab will assume that you have this background information.</li>
</ul>
<div id="merges-and-merge-conflicts" class="section level2">
<h2>Merges and merge conflicts</h2>
<p>This is the first time you’re working in teams, so we’re going to make things a little more interesting and let all of you make changes and push those changes to your team repository.
Sometimes things will go swimmingly, and sometimes you’ll run into merge conflicts.
So our first task today is to walk you through a merge conflict!</p>
<ul>
<li>Pushing to a repo replaces the code on GitHub with the code you have on your computer.</li>
<li>If a collaborator has made a change to your repo on GitHub that you haven’t incorporated into your local work, GitHub will stop you from pushing to the repo because this could overwrite your collaborator’s work!</li>
<li>So you need to explicitly “merge” your collaborator’s work before you can push.</li>
<li>If your and your collaborator’s changes are in different files or in different parts of the same file, git merges the work for you automatically when you *pull*.</li>
<li>If you both changed the same part of a file, git will produce a **merge conflict** because it doesn’t know how which change you want to keep and which change you want to overwrite.</li>
</ul>
<p>Git will put conflict markers in your code that look like:</p>
<pre><code>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD 

See also: [dplyr documentation](https://dplyr.tidyverse.org/)   

======= 

See also [ggplot2 documentation](https://ggplot2.tidyverse.org/)  

&gt;&gt;&gt;&gt;&gt;&gt;&gt; some1alpha2numeric3string4</code></pre>
<p>The <code>===</code>s separate <em>your</em> changes (top) from <em>their</em> changes (bottom).</p>
<p>Note that on top you see the word <code>HEAD</code>, which indicates that these are your changes.</p>
<p>And at the bottom you see <code>some1alpha2numeric3string4</code> (well, it probably looks more like <code>28e7b2ceb39972085a0860892062810fb812a08f</code>).</p>
<p>This is the <strong>hash</strong> (a unique identifier) of the commit your collaborator made with the conflicting change.</p>
<p>Your job is to <em>reconcile</em> the changes: edit the file so that it incorporates the best of both versions and delete the <code>&lt;&lt;&lt;</code>, <code>===</code>, and <code>&gt;&gt;&gt;</code> lines.
Then you can stage and commit the result.</p>
</div>
</div>
<div id="merge-conflict-activity" class="section level1">
<h1>Merge conflict activity</h1>
<div id="setup" class="section level2">
<h2>Setup</h2>
<ul>
<li>Clone the repo and open the .Rmd file.</li>
<li>Assign the numbers 1, 2, 3, and 4 to each of the team members. If your team has fewer than 4 people, some people will need to have multiple numbers. If your team has more than 4 people, some people will need to share some numbers.</li>
</ul>
</div>
<div id="lets-cause-a-merge-conflict" class="section level2">
<h2>Let’s cause a merge conflict!</h2>
<p>Our goal is to see two different types of merges: first we’ll see a type of merge that git can’t figure out on its own how to do on its own (a <strong>merge conflict</strong>) and requires human intervention, then another type of where that git can figure out how to do without human intervention.</p>
<p>Doing this will require some tight choreography, so pay attention!</p>
<p>Take turns in completing the exercise, only one member at a time.
<strong>Others should just watch, not doing anything on their own projects (this includes not even pulling changes!)</strong> until they are instructed to.
If you feel like you won’t be able to resist the urge to touch your computer when it’s not your turn, we recommend putting your hands in your pockets or sitting on them!</p>
<p><strong>Before starting</strong>: everyone should have the repo cloned and know which role number(s) they are.</p>
<p><strong>Role 1:</strong></p>
<ul>
<li>Change the team name to your actual team name.</li>
<li>Knit, commit, push.</li>
</ul>
<p>🛑 Make sure the previous role has finished before moving on to the next step.</p>
<p><strong>Role 2:</strong></p>
<ul>
<li>Change the team name to some other word.</li>
<li>Knit, commit, push. You should get an error.</li>
<li>Pull. Take a look at the document with the merge conflict.</li>
<li>Clear the merge conflict by editing the document to choose the correct/preferred change.</li>
<li>Knit.</li>
<li><strong>Click the Stage checkbox</strong> for all files in your Git tab. Make sure they all have check marks, not filled-in boxes.</li>
<li>Commit and push.</li>
</ul>
<p>🛑 Make sure the previous role has finished before moving on to the next step.</p>
<p><strong>Role 3:</strong></p>
<ul>
<li>Change the a label of the first code chunk</li>
<li>Knit, commit, push. You should get an error.</li>
<li>Pull. No merge conflicts should occur, but you should see a message about merging.</li>
<li>Now push.</li>
</ul>
<p>🛑 Make sure the previous role has finished before moving on to the next step.</p>
<p><strong>Role 4:</strong></p>
<ul>
<li>Change the label of the first code chunk to something other than previous role did.</li>
<li>Knit, commit, push. You should get an error.</li>
<li>Pull. Take a look at the document with the merge conflict. Clear the merge conflict by choosing the correct/preferred change. Commit, and push.</li>
</ul>
<p>🛑 Make sure the previous role has finished before moving on to the next step.</p>
<p><strong>Everyone:</strong> Pull, and observe the changes in your document.</p>
</div>
<div id="tips-for-collaborating-via-github" class="section level2">
<h2>Tips for collaborating via GitHub</h2>
<ul>
<li>Always pull first before you start working.</li>
<li>Resolve a merge conflict (commit and push) <em>before</em> continuing your work. Never do new work while resolving a merge conflict.</li>
<li>Knit, commit, and push often to minimize merge conflicts and/or to make merge conflicts easier to resolve.</li>
<li>If you find yourself in a situation that is difficult to resolve, ask questions ASAP. Don’t let it linger and get bigger.</li>
</ul>
</div>
</div>
<div id="getting-started" class="section level1">
<h1>Getting started</h1>
<p>Go to the course GitHub organization and locate your lab repo, which should be named <code>lab1-YourTeamNumber</code>.
Grab the URL of the repo, and clone it in RStudio.
First, open the R Markdown document <code>lab1.Rmd</code> and Knit it.
Make sure it compiles without errors.
The output will be in the file markdown <code>.md</code> file with the same name.</p>
<div id="warm-up" class="section level2">
<h2>Warm up</h2>
<p>Before we introduce the data, let’s warm up with some simple exercises.</p>
<ul>
<li>Update the YAML, changing the author name to your team number (e.g., “Team 1”), and <strong>knit</strong> the document.</li>
<li>Commit your changes with a meaningful commit message.</li>
<li>Push your changes to GitHub.</li>
<li>Go to your repo on GitHub and confirm that your changes are visible in your Rmd <strong>and</strong> md files. If anything is missing, commit and push again.</li>
</ul>
</div>
<div id="packages" class="section level2">
<h2>Packages</h2>
<p>We’ll use the <strong>tidyverse</strong> package for much of the data wrangling.
You can load them by running the following in your Console:</p>
<pre class="r"><code>library(tidyverse)</code></pre>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<p>The dataset for this assignment can be found as a CSv (comma separated values) file in the <code>data</code> folder of your repository.
You can read it in using the following.</p>
<pre class="r"><code>nobel &lt;- read_csv(&quot;data/nobel.csv&quot;) # Or, you can use nobel &lt;- ezpickr::pick(&quot;data/nobel.csv&quot;)</code></pre>
<p>The variable descriptions are as follows:</p>
<ul>
<li><code>id</code>: ID number</li>
<li><code>firstname</code>: First name of laureate</li>
<li><code>surname</code>: Surname</li>
<li><code>year</code>: Year prize won</li>
<li><code>category</code>: Category of prize</li>
<li><code>affiliation</code>: Affiliation of laureate</li>
<li><code>city</code>: City of laureate in prize year</li>
<li><code>country</code>: Country of laureate in prize year</li>
<li><code>born_date</code>: Birth date of laureate</li>
<li><code>died_date</code>: Death date of laureate</li>
<li><code>gender</code>: Gender of laureate</li>
<li><code>born_city</code>: City where laureate was born</li>
<li><code>born_country</code>: Country where laureate was born</li>
<li><code>born_country_code</code>: Code of country where laureate was born</li>
<li><code>died_city</code>: City where laureate died</li>
<li><code>died_country</code>: Country where laureate died</li>
<li><code>died_country_code</code>: Code of country where laureate died</li>
<li><code>overall_motivation</code>: Overall motivation for recognition</li>
<li><code>share</code>: Number of other winners award is shared with</li>
<li><code>motivation</code>: Motivation for recognition</li>
</ul>
<p>In a few cases the name of the city/country changed after laureate was given (e.g. in 1975 Bosnia and Herzegovina was called the Socialist Federative Republic of Yugoslavia).
In these cases the variables below reflect a different name than their counterparts without the suffix `_original`.</p>
<ul>
<li><code>born_country_original</code>: Original country where laureate was born</li>
<li><code>born_city_original</code>: Original city where laureate was born</li>
<li><code>died_country_original</code>: Original country where laureate died</li>
<li><code>died_city_original</code>: Original city where laureate died</li>
<li><code>city_original</code>: Original city where laureate lived at the time of winning the award</li>
<li><code>country_original</code>: Original country where laureate lived at the time of winning the award</li>
</ul>
</div>
</div>
<div id="exercises" class="section level1">
<h1>Exercises</h1>
<p>Take turns answering the exercises.
Make sure each team member gets to commit to the repo by the time you submit your work.
And make sure that the person taking the lead for an exercise is sharing their screen.
You don’t have to switch at each exercise, you can find your a cadence that works for your team and stick to it.</p>
<div id="get-to-know-your-data" class="section level2">
<h2>Get to know your data</h2>
<ol style="list-style-type: decimal">
<li>How many observations and how many variables are in the dataset? Use inline code to answer this question. What does each row represent?</li>
</ol>
<p>There are some observations in this dataset that we will exclude from our analysis to match the Buzzfeed results.</p>
<pre class="r"><code>nobel</code></pre>
<pre><code>## # A tibble: 935 x 26
##       id firstname  surname  year category affiliation  city  country born_date 
##    &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;        &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;    
##  1     1 Wilhelm C~ Röntgen  1901 Physics  Munich Univ~ Muni~ Germany 1845-03-27
##  2     2 Hendrik A. Lorentz  1902 Physics  Leiden Univ~ Leid~ Nether~ 1853-07-18
##  3     3 Pieter     Zeeman   1902 Physics  Amsterdam U~ Amst~ Nether~ 1865-05-25
##  4     4 Henri      Becque~  1903 Physics  École Polyt~ Paris France  1852-12-15
##  5     5 Pierre     Curie    1903 Physics  École munic~ Paris France  1859-05-15
##  6     6 Marie      Curie    1903 Physics  &lt;NA&gt;         &lt;NA&gt;  &lt;NA&gt;    1867-11-07
##  7     6 Marie      Curie    1911 Chemist~ Sorbonne Un~ Paris France  1867-11-07
##  8     8 Lord       Raylei~  1904 Physics  Royal Insti~ Lond~ United~ 1842-11-12
##  9     9 Philipp    Lenard   1905 Physics  Kiel Univer~ Kiel  Germany 1862-06-07
## 10    10 J.J.       Thomson  1906 Physics  University ~ Camb~ United~ 1856-12-18
## # ... with 925 more rows, and 17 more variables: died_date &lt;date&gt;,
## #   gender &lt;chr&gt;, born_city &lt;chr&gt;, born_country &lt;chr&gt;, born_country_code &lt;chr&gt;,
## #   died_city &lt;chr&gt;, died_country &lt;chr&gt;, died_country_code &lt;chr&gt;,
## #   overall_motivation &lt;chr&gt;, share &lt;dbl&gt;, motivation &lt;chr&gt;,
## #   born_country_original &lt;chr&gt;, born_city_original &lt;chr&gt;,
## #   died_country_original &lt;chr&gt;, died_city_original &lt;chr&gt;, city_original &lt;chr&gt;,
## #   country_original &lt;chr&gt;</code></pre>
<pre class="r"><code>nrow(nobel)</code></pre>
<pre><code>## [1] 935</code></pre>
<pre class="r"><code>ncol(nobel)</code></pre>
<pre><code>## [1] 26</code></pre>
<p>**We have 935 observations and 26 variables.
Each row represents information about the laureates who won the Nobel prize.</p>
<ol start="2" style="list-style-type: decimal">
<li>[Answer is provided below] Create a new data frame called <code>nobel_living</code> that filters for</li>
</ol>
<ul>
<li>laureates for whom <code>country</code> is available</li>
<li>laureates who are people as opposed to organizations (organizations are denoted with <code>"org"</code> as their <code>gender</code>)</li>
<li>laureates who are still alive (their <code>died_date</code> is <code>NA</code>)</li>
</ul>
<pre class="r"><code>nobel_living &lt;- nobel %&gt;%
  filter(
    !is.na(country),
    gender != &quot;org&quot;,
    is.na(died_date)
  )

nobel_living</code></pre>
<pre><code>## # A tibble: 228 x 26
##       id firstname   surname  year category affiliation city  country born_date 
##    &lt;dbl&gt; &lt;chr&gt;       &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt;   &lt;date&gt;    
##  1    68 Chen Ning   Yang     1957 Physics  Institute ~ Prin~ USA     1922-09-22
##  2    69 Tsung-Dao   Lee      1957 Physics  Columbia U~ New ~ USA     1926-11-24
##  3    95 Leon N.     Cooper   1972 Physics  Brown Univ~ Prov~ USA     1930-02-28
##  4    97 Leo         Esaki    1973 Physics  IBM Thomas~ York~ USA     1925-03-12
##  5    98 Ivar        Giaever  1973 Physics  General El~ Sche~ USA     1929-04-05
##  6    99 Brian D.    Joseph~  1973 Physics  University~ Camb~ United~ 1940-01-04
##  7   101 Antony      Hewish   1974 Physics  University~ Camb~ United~ 1924-05-11
##  8   103 Ben R.      Mottel~  1975 Physics  Nordita     Cope~ Denmark 1926-07-09
##  9   106 Samuel C.C. Ting     1976 Physics  Massachuse~ Camb~ USA     1936-01-27
## 10   107 Philip W.   Anders~  1977 Physics  Bell Telep~ Murr~ USA     1923-12-13
## # ... with 218 more rows, and 17 more variables: died_date &lt;date&gt;,
## #   gender &lt;chr&gt;, born_city &lt;chr&gt;, born_country &lt;chr&gt;, born_country_code &lt;chr&gt;,
## #   died_city &lt;chr&gt;, died_country &lt;chr&gt;, died_country_code &lt;chr&gt;,
## #   overall_motivation &lt;chr&gt;, share &lt;dbl&gt;, motivation &lt;chr&gt;,
## #   born_country_original &lt;chr&gt;, born_city_original &lt;chr&gt;,
## #   died_country_original &lt;chr&gt;, died_city_original &lt;chr&gt;, city_original &lt;chr&gt;,
## #   country_original &lt;chr&gt;</code></pre>
<pre class="r"><code>nrow(nobel_living)</code></pre>
<pre><code>## [1] 228</code></pre>
<p>Confirm that once you have filtered for these characteristics you are left with a data frame with 228 observations, once again using inline code.</p>
<p>🧶 ✅ ⬆️ Knit, <em>commit, and push your changes to GitHub with an appropriate commit message. Make sure to commit and push all changed files so that your Git pane is cleared up afterwards.</em></p>
</div>
<div id="most-living-nobel-laureates-were-based-in-the-us-when-they-won-their-prizes" class="section level2">
<h2>Most living Nobel laureates were based in the US when they won their prizes</h2>
<p>… says the Buzzfeed article.
Let’s see if that’s true.</p>
<p>First, we’ll create a new variable to identify whether the laureate was in the US when they won their prize.
We’ll use the <code>mutate()</code> function for this.
The following pipeline mutates the <code>nobel_living</code> data frame by adding a new variable called <code>country_us</code>.
We use an if statement to create this variable.
The first argument in the <code>if_else()</code> function we’re using to write this if statement is the condition we’re testing for.
If <code>country</code> is equal to <code>"USA"</code>, we set <code>country_us</code> to <code>"USA"</code>.
If not, we set the <code>country_us</code> to <code>"Other"</code>.</p>
<pre class="marginfigure"><code>Note that we can achieve the same result using the `fct_other()` function we&#39;ve seen before (i.e. with `country_us = fct_other(country, &quot;USA&quot;)`). We decided to use the `if_else()` here to show you one example of an if statement in R.</code></pre>
<pre class="r"><code>nobel_living &lt;- nobel_living %&gt;%
  mutate(
    country_us = if_else(country == &quot;USA&quot;, &quot;USA&quot;, &quot;Other&quot;)
  )</code></pre>
<p>Next, we will limit our analysis to only the following categories: Physics, Medicine, Chemistry, and Economics.</p>
<pre class="r"><code>nobel_living_science &lt;- nobel_living %&gt;%
  filter(category %in% c(&quot;Physics&quot;, &quot;Medicine&quot;, &quot;Chemistry&quot;, &quot;Economics&quot;))</code></pre>
<p>For the next exercise work with the <code>nobel_living_science</code> data frame you created above.
This means you’ll need to define this data frame in your R Markdown document, even though the next exercise doesn’t explicitly ask you to do so.</p>
<ol start="3" style="list-style-type: decimal">
<li><p>Create a faceted bar plot visualizing the relationship between the category of prize and whether the laureate was in the US when they won the nobel prize.
Interpret your visualization, and say a few words about whether the Buzzfeed headline is supported by the data.</p>
<ul>
<li>Your visualization should be faceted by category.</li>
<li>For each facet you should have two bars, one for winners in the US and one for Other.</li>
<li>Flip the coordinates so the bars are horizontal, not vertical.</li>
</ul></li>
</ol>
<p>🧶 ✅ ⬆️ Knit, <em>commit, and push your changes to GitHub with an appropriate commit message. Make sure to commit and push all changed files so that your Git pane is cleared up afterwards.d</em></p>
</div>
<div id="but-of-those-us-based-nobel-laureates-many-were-born-in-other-countries" class="section level2">
<h2>But of those US-based Nobel laureates, many were born in other countries</h2>
<pre class="marginfigure"><code>**Hint:** You should be able to ~~cheat~~ borrow from code you used earlier to create the `country_us` variable.</code></pre>
<pre class="r"><code>ggplot(nobel_living, aes(y = country_us, fill = country_us)) +
  geom_bar() +
  facet_wrap(~category)</code></pre>
<p><img src="/2022/02/15/is-407-hw-02/index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>**As You can see on the bar chart, when laureates won the each Nobel Prize, there are more people staying in the United States than in other countries. Therefore, as described in the article, accommodating refugees can increase the rate of receiving Nobel Prizes in the United States.</p>
<ol start="4" style="list-style-type: decimal">
<li>Create a new variable called <code>born_country_us</code> that has the value <code>"USA"</code> if the laureate is born in the US, and <code>"Other"</code> otherwise.
How many of the winners are born in the US?</li>
</ol>
<pre class="r"><code>nobel_living &lt;- nobel_living %&gt;%
  mutate(
    born_country_us = if_else(born_country_original == &quot;USA&quot;, &quot;USA&quot;, &quot;Other&quot;)
  )</code></pre>
<pre class="r"><code>ggplot(nobel_living, aes(y = born_country_us, fill = born_country_us)) +
  geom_bar() +
  facet_wrap(~category)</code></pre>
<p><img src="/2022/02/15/is-407-hw-02/index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>**Contrary to Exercise 3, the Bar chart shows that people from other countries received much more Nobel prize than those from the United States in all categories except for the Economics.</p>
<pre class="r"><code>born_country_us_count &lt;- nobel_living %&gt;%
  filter(
    born_country_us == &quot;USA&quot;,
  )</code></pre>
<p>*We got 105 winners are born in the US.</p>
<ol start="5" style="list-style-type: decimal">
<li><p>Add a second variable to your visualization from Exercise 3 based on whether the laureate was born in the US or not.
Based on your visualization, do the data appear to support Buzzfeed’s claim?
Explain your reasoning in 1-2 sentences.</p>
<ul>
<li>Your final visualization should contain a facet for each category.</li>
<li>Within each facet, there should be a bar for whether the laureate won the award in the US or not.</li>
<li>Each bar should have segments for whether the laureate was born in the US or not.</li>
</ul></li>
</ol>
<p>🧶 ✅ ⬆️ Knit, <em>commit, and push your changes to GitHub with an appropriate commit message. Make sure to commit and push all changed files so that your Git pane is cleared up afterwards.</em></p>
</div>
<div id="heres-where-those-immigrant-nobelists-were-born" class="section level2">
<h2>Here’s where those immigrant Nobelists were born</h2>
<pre class="marginfigure"><code>Note that your bar plot won&#39;t exactly match the one from the Buzzfeed article. This is likely because the data has been updated since the article was published.</code></pre>
<pre class="r"><code>ggplot(nobel_living, aes(x =  born_country_us, y = country_us, fill = country_us)) +
  geom_bar(stat=&#39;identity&#39;)+
  facet_wrap(~category)</code></pre>
<p><img src="/2022/02/15/is-407-hw-02/index_files/figure-html/unnamed-chunk-12-1.png" width="672" />
**According to this bar graph, many other counties’ laureates switch their country to USA.</p>
<ol start="6" style="list-style-type: decimal">
<li>In a single pipeline, filter for laureates who won their prize in the US, but were born outside of the US, and then create a frequency table (with the <code>count()</code> function) for their birth country (<code>born_country</code>) and arrange the resulting data frame in descending order of number of observations for each country. Which country is the most common?</li>
</ol>
<pre class="r"><code>nobel_final &lt;- nobel %&gt;%
  filter(
    country == &quot;USA&quot;,
    born_country != &quot;USA&quot;)

nobel_final %&gt;% 
  count(born_country) %&gt;%
  arrange(desc(n))</code></pre>
<pre><code>## # A tibble: 37 x 2
##    born_country       n
##    &lt;chr&gt;          &lt;int&gt;
##  1 United Kingdom    15
##  2 Canada            12
##  3 Germany           10
##  4 China              6
##  5 Poland             6
##  6 France             5
##  7 Italy              5
##  8 Japan              5
##  9 Austria            4
## 10 Hungary            4
## # ... with 27 more rows</code></pre>
<p>**The data shows that UK is the most common country.</p>
<p>🧶 ✅ ⬆️ Knit, <em>commit, and push your changes to GitHub with an appropriate commit message. Make sure to commit and push all changed files so that your Git pane is cleared up afterwards and review the md document on GitHub to make sure you’re happy with the final state of your work.</em></p>
<p>Now go back through your write up to make sure you’ve answered all questions and all of your R chunks are properly labelled.
Once you decide as a team that you’re done with this lab, all members of the team should pull the changes and knit the R Markdown document to confirm that they can reproduce the report.</p>
</div>
</div>
<div id="interested-in-how-buzzfeed-made-their-visualizations" class="section level1">
<h1>Interested in how Buzzfeed made their visualizations?</h1>
<p>The plots in the Buzzfeed article are called waffle plots.
You can find the code used for making these plots in Buzzfeed’s GitHub repo (yes, they have one!) <a href="https://buzzfeednews.github.io/2017-01-immigration-and-science/">here</a>.
You’re not expected to recreate them as part of your assignment, but you’re welcomed to do so for fun!</p>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    

    
  </body>
</html>

